### PR TITLE
fix(enablebanking): synthesise stable transaction ID when entry_refer…

### LINKED ISSUE #154: EB: Possible DNB duplicate transactions
**Observed**

EnableBanking reader & DNB Bank account. After the last commit, I deleted my session due to the breaking change, rebuilt from HEAD and ran ynabber. I *think* I observed some duplicate transactions in Ynabber that I didn't think about at the time. I just tidied and went on with life.

**Expected**

No duplicates from DNB, when changing sessions. We've already ensured to only import transactions with status "BOOK", but there's potentially another issue to investigate.

**Possible Cause / Solutions**

For my Sparebanken & Credit card accounts, the `/transactions` API response returns a unique value in `entry_reference`.
But for DNB, then `entry_reference` is set to null
API docs here: https://enablebanking.com/docs/api/reference/#transaction

I need to remind myself of what strategy is currently applied when `entry_reference` is null. I suspect that we fall back to `transaction_id` which is not stable across sessions.

I think this means that ynabber needs to synthesise its own unique transaction identifier in situations where `entry_reference` is `null`, using other data from the transaction, in a fashion that is deterministic across sessions.

### PR DESCRIPTION
**Pull request by linkmic**
**Problem**
 
DNB returns `entry_reference: null` and a session-scoped `transaction_id` 
Using it as the YNAB import ID causes duplicate transactions when the session is reset.
   
Closes #154
   
**Solution**
   
Priority chain in resolveTransactionID - always returns a non-empty, session-independent string:
      
    1. `entry_reference`: bank-assigned, stable (tested: Sparebanken, SAS Credit Card)
    2. `reference_number`: bank-assigned, stable (future-proofing; null for all observed ASPSPs today)
    3. `syntheticTransactionID`: experimental, deterministic SHA-256 of booking_date + amount + currency + credit_debit_indicator + remittance_information, NUL-separated, prefixed synth:

There's a risk of a duplicate transaction in YNAB if any of the fields used to create syntheticTransactionID change their value from session to session. The session-scoped `transaction_id` is intentionally excluded.
   
**Changes**   
    - mapper.go: resolveTransactionID + syntheticTransactionID
    - transaction_id_test.go: new: covers all three ASPSP shapes, fallback paths, determinism, collision 
  resistance
    - enablebanking_test.go: mapper smoke-test uses entry_reference instead of transaction_id

### CODE REVIEW

File: reader/enablebanking/mapper.go [hunk 1]
```diff
@@ -84,17 +82,55 @@ func (r Reader) defaultMapper(account AccountInfo, tx EBTransaction) (*ynabber.T
...
+// logs and makes the origin of the value unambiguous.
+func syntheticTransactionID(tx EBTransaction) string {
+	parts := []string{
+		tx.BookingDate,
+		tx.TransactionAmount.Amount,
+		tx.TransactionAmount.Currency,
+		tx.CreditDebitIndicator,
+		strings.Join(tx.RemittanceInformation, "\x00"),
+	}
+	h := sha256.Sum256([]byte(strings.Join(parts, "\x00")))
```
Comment (martinohansen) [inline reader/enablebanking/mapper.go]: Its safter to concat with json, and its less obscure:

```
b, _ := json.Marshal(parts)
h := sha256.Sum256(b)
